[tool.poetry]
name = "repo"
version = "0.1.0"
description = ""
authors = ["Mar Sánchez <sanchezm@washpost.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.4.6"
pandas = "^1.4.4"
numpy = "^1.23.3"
matplotlib = "^3.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
